package zhao.blog.managementsystem.entity;
// Generated 2017-7-24 20:10:01 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Album generated by hbm2java
 */
public class Album implements java.io.Serializable {

	private Integer id;
	private String title;
	private String image;
	private String content;
	private String notice;
	private Date time;
	private Set photos = new HashSet(0);

	public Album() {
	}

	public Album(String title, String image, String content, String notice, Date time) {
		this.title = title;
		this.image = image;
		this.content = content;
		this.notice = notice;
		this.time = time;
	}

	public Album(String title, String image, String content, String notice, Date time, Set photos) {
		this.title = title;
		this.image = image;
		this.content = content;
		this.notice = notice;
		this.time = time;
		this.photos = photos;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Set getPhotos() {
		return this.photos;
	}

	public void setPhotos(Set photos) {
		this.photos = photos;
	}

}
