package zhao.blog.managementsystem.entity;
// Generated 2017-7-24 20:10:01 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * Daily generated by hbm2java
 */
public class Daily implements java.io.Serializable {

	private Integer id;
	private String content;
	private Date time;
	private String description;

	public Daily() {
	}

	public Daily(String content, Date time) {
		this.content = content;
		this.time = time;
	}

	public Daily(String content, Date time, String description) {
		this.content = content;
		this.time = time;
		this.description = description;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
