package zhao.blog.managementsystem.entity;
// Generated 2017-7-24 20:10:01 by Hibernate Tools 4.0.0.Final

/**
 * Me generated by hbm2java
 */
public class Me implements java.io.Serializable {

	private Integer id;
	private String content;
	private String name;
	private String notice;

	public Me() {
	}

	public Me(String content, String name, String notice) {
		this.content = content;
		this.name = name;
		this.notice = notice;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNotice() {
		return this.notice;
	}

	public void setNotice(String notice) {
		this.notice = notice;
	}

}
