package zhao.blog.managementsystem.entity;
// Generated 2017-7-24 20:10:01 by Hibernate Tools 4.0.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private String name;
	private String account;
	private String password;
	private String sex;
	private String headpic;
	private String contact;
	private Date birth;
	private String hobby;
	private String homepage;
	private String desciption;
	private Date createdate;
	private Set critiques = new HashSet(0);

	public User() {
	}

	public User(String account, String password, String sex, Date createdate) {
		this.account = account;
		this.password = password;
		this.sex = sex;
		this.createdate = createdate;
	}

	public User(String name, String account, String password, String sex, String headpic, String contact, Date birth,
			String hobby, String homepage, String desciption, Date createdate, Set critiques) {
		this.name = name;
		this.account = account;
		this.password = password;
		this.sex = sex;
		this.headpic = headpic;
		this.contact = contact;
		this.birth = birth;
		this.hobby = hobby;
		this.homepage = homepage;
		this.desciption = desciption;
		this.createdate = createdate;
		this.critiques = critiques;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAccount() {
		return this.account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getHeadpic() {
		return this.headpic;
	}

	public void setHeadpic(String headpic) {
		this.headpic = headpic;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public Date getBirth() {
		return this.birth;
	}

	public void setBirth(Date birth) {
		this.birth = birth;
	}

	public String getHobby() {
		return this.hobby;
	}

	public void setHobby(String hobby) {
		this.hobby = hobby;
	}

	public String getHomepage() {
		return this.homepage;
	}

	public void setHomepage(String homepage) {
		this.homepage = homepage;
	}

	public String getDesciption() {
		return this.desciption;
	}

	public void setDesciption(String desciption) {
		this.desciption = desciption;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Set getCritiques() {
		return this.critiques;
	}

	public void setCritiques(Set critiques) {
		this.critiques = critiques;
	}

}
